### PR TITLE
docs: Fix typo

### PR DESCRIPTION
**Pull request by nbergqui**

### CODE REVIEW

**Comment by jtrussell** [comment]
Haha, nice. Thanks!

**Comment by nbergqui** [comment]
No problem. Trying to get more familiar with GitHub and this seemed like an opportunity to try branching and creating a pull request.

**Comment by jtrussell** [comment]
It was much appreciated :octocat:.

(Just in case my meaning got muddled I was chuckling at the nature of the typo not anything you did)

**Comment by nbergqui** [comment]
No muddling here. I thought it was funny too. That release note caught my eye because I added the "numeric id" feature to a local copy of the code, but never got it fully working with expandTo(). The v1.0.2 release seemed to fix my problem.

**Pull request merged**
