### PR TITLE
V2: Add transcluded scope for inline node templates. Unit tests covering trvw controller as well as transcluded scope feature.

### PR DESCRIPTION
**Pull request by christophercr**
To continue with the release of v2, new tests are added for the treeview controller (trvw) methods.

### CODE REVIEW

**Comment by christophercr** [comment]
Unit tests covering changes in https://github.com/iVantage/angular-ivh-treeview/pull/158

**Comment by christophercr** [comment]
Solves the issue iVantage#81

**Comment by jtrussell** [comment]
Merged and published under v2.0.0-alpha.2. Thanks for your efforts :).

**Comment by christophercr** [comment]
Hi again, I noticed that this PR was not merged.... I double checked the code and the changes are not there. Probably something went wrong when you merged? Can you please have a look?

**Comment by jtrussell** [comment]
Sorry, published to npm but forgot to push. Should be there now :).

**Comment by christophercr** [comment]
Oh I see... no problem. Thanks! ;)

**Pull request closed without merging**
